/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestOrewaRouteImport } from './routes/_guest/orewa'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestOrewaRoute = GuestOrewaRouteImport.update({
  id: '/orewa',
  path: '/orewa',
  getParentRoute: () => GuestRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestRouteRouteWithChildren
  '/orewa': typeof GuestOrewaRoute
}
export interface FileRoutesByTo {
  '/': typeof GuestRouteRouteWithChildren
  '/orewa': typeof GuestOrewaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRoute
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_guest/orewa': typeof GuestOrewaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orewa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orewa'
  id: '__root__' | '/_auth' | '/_guest' | '/_guest/orewa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRoute
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/orewa': {
      id: '/_guest/orewa'
      path: '/orewa'
      fullPath: '/orewa'
      preLoaderRoute: typeof GuestOrewaRouteImport
      parentRoute: typeof GuestRouteRoute
    }
  }
}

interface GuestRouteRouteChildren {
  GuestOrewaRoute: typeof GuestOrewaRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestOrewaRoute: GuestOrewaRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRoute,
  GuestRouteRoute: GuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
